# Install Config for @ ${dhost}:$(tStamp)\n" -- ZFS, because YAML is dynamic, not all attributes are common.
install: ${dpath}
  disks: 
    - ${disk}3
    pool: ${dpool}
    dataset: ${ddataset}
    format: ZFS
    compression: lz4
      encryption: aes-gcm-256
      key: /srv/crypto/zfs.key
  source:
    host: root@localhost
    dataset: ${spath}
    type: ZFS
  kernel: 6.1.1-gentoo
  boot: EFI
  partition: ${disk}2
  swap: file
    location: ${dpool}/swap
    format: funnyBone
  profile: ${sprofile}
  bootloader: refind
